name = "TestPkg"
uuid = "3bb6f468-dcc6-4571-af79-74bf25fc8527"
authors = ["Gilga"]
version = "0.1.0"

[compat]
julia = "1.3.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
